# Generated by Django 3.0.6 on 2020-05-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('FR', 'Father'), ('MR', 'Mother'), ('HB', 'Husband'), ('BR', 'Brother'), ('SR', 'Sister'), ('FN', 'Friend'), ('RL', 'Relative'), ('OT', 'Other')], default='FR', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Emergency_Contact')),
            ],
        ),
    ]
