# Generated by Django 3.0.6 on 2020-05-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200520_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Emergency_Contact',
        ),
    ]
