# Generated by Django 3.0.6 on 2020-05-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
