# Generated by Django 3.0.6 on 2020-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200522_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='curr_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
