# Generated by Django 3.0.6 on 2020-05-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200522_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='curr_user',
            new_name='user',
        ),
    ]
